language: python
sudo: required

# use an older trusty image, because the newer images cause build errors with
# psycopg2 that comes with CKAN<2.8:
#   "Error: could not determine PostgreSQL version from '10.1'"
# see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

# matrix
python:
  - 2.7
env:
  - CKANVERSION=2.7

# tests
services:
  - postgresql
  - redis
install:
  - bash bin/travis-build.bash
script: sh bin/travis-run.sh
